### ISSUE TITLE
请求 提供国内云盘数据集下载方式

### ISSUE THREAD

**Issue by htthYjh** [ChuXiaokai/baidu_ultr_dataset#3]
你好，很开心了解到你们的项目，希望能提供国内网盘数据集下载方式，非常感谢。

**Comment by HaitaoMao** [comment]
您好，这里是我们的数据集主页，这里有在国内的下载链接 https://searchscience.baidu.com/dataset_ultr.html#download

**Comment by HaitaoMao** [comment]
Solved
