### ISSUE TITLE
运行中遇到的bug

### ISSUE THREAD

**Issue by jinbaobaojhr** [ChuXiaokai/baidu_ultr_dataset#8]
主办方你好，我在运行unbiased_learning.py的时候，代码会有如下报错：
![image](https://user-images.githubusercontent.com/57559447/200179450-a87a4da0-09fa-4cf2-8450-2c990242efaf.png)

我看了一下可能是因为BaseAlgorithm类继承的是ABC，而不是nn.Module，所以它没有state_dict.
请问这个可以怎么解决，要修改代码框架吗

**Comment by ChuXiaokai** [comment]
抱歉，这里是我们的疏忽，应改为
```python
   torch.save(model.model.state_dict(),
              'save_model/save_steps{}_{:.5f}_{:5f}.model'.format(idx, result_dict_ann['pnr'], result_dict_click['pnr'])
    )
```
此外，对于DLA方法，如果你想要断点训练的话，可能还需要保存对应的propensity model
```python
   torch.save(model.propensity_model.state_dict(), "your_path"))
```
祝你取得好成绩~

**Comment by jinbaobaojhr** [comment]
> 抱歉，这里是我们的疏忽，应改为
> 
> ```python
>    torch.save(model.model.state_dict(),
>               'save_model/save_steps{}_{:.5f}_{:5f}.model'.format(idx, result_dict_ann['pnr'], result_dict_click['pnr'])
>     )
> ```
> 
> 此外，对于DLA方法，如果你想要断点训练的话，可能还需要保存对应的propensity model
> 
> ```python
>    torch.save(model.propensity_model.state_dict(), "your_path"))
> ```
> 
> 祝你取得好成绩~

好的，谢谢~
