### ISSUE TITLE
Found different queries  share same qids

### ISSUE THREAD

**Issue by gluver** [ChuXiaokai/baidu_ultr_dataset#9]
Hi, in file [annotation_data_0522.txt ](https://drive.google.com/file/d/1hdWRRSMrCnQxilYfjTx8RhW3XTgiSd9Q/view)(or [ test_data.txt](https://searchscience.baidu.com/baidu_ultr/labeled_dataset/test_data.txt)) ,observed that some lines share the same qids but with different query token sequence, for example in 389292 and 389293:
![image](https://user-images.githubusercontent.com/29994223/204094316-194a4097-ecfa-4950-9c46-ddaddb72af1d.png)
in line 389471 and 389472
![image](https://user-images.githubusercontent.com/29994223/204094443-e711b2c2-5b20-40d4-a3b6-ad28b5400d0e.png)

 Such issue is also found in the [wsdm_test_1.txt](https://bj.bcebos.com/v1/ai-studio-online/2cd7df56206d4e50be0f3a58e53a0236d7eab0cd9ad94f9d82afddba361aa479?responseContentDisposition=attachment%3B%20filename%3Dwsdm_test_1.txt&authorization=bce-auth-v1%2F5cfe9a5e1454405eb2a975c43eace6ec%2F2022-09-14T15%3A30%3A16Z%2F-1%2F%2Feae14185e8787d435e4720811fd707447593c1e6a7b24903daf99684a6391c95) used for generate subimission, will it affect the online evaluation metrics?

**Comment by zoulixin93** [comment]
You are a really careful contestant. There are 8% of queries with the same qids in the test dataset. It will slightly influence the ranking score. We have updated the test script on the competition platform. And we will update the github as soon as possible.
Wish you get a good score!
